name: Perldoc
version: 0.11
abstract: Perl 6 Documentation System
author: Sam Vilain <samv@cpan.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.54
requires:
  perl: 5.6.1
  Data::Dumper: 0
  Scalar::Util: 0
  Set::Object: 1.10
  Maptastic: 1.00
  Tree::DAG_Node: 0
  Spiffy: 0
  YAML: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
